### PR TITLE
Add "Link to Image" link

### PR DESCRIPTION
**Pull request by jihchi**
I made a service which can generate and output JPG from mermaid code.

### Screenshot (Live Editor)
screenshot_2019-05-17 18-28-28

### Image ([mermaid.ink](https://mermaid.ink/img/c2VxdWVuY2VEaWFncmFtCiAgICBwYXJ0aWNpcGFudCBBbGljZQogICAgcGFydGljaXBhbnQgQm9iCiAgICBBbGljZS0-Sm9objogSGVsbG8gSm9obiwgaG93IGFyZSB5b3U_CiAgICBsb29wIEhlYWx0aGNoZWNrCiAgICAgICAgSm9obi0-Sm9objogRmlnaHQgYWdhaW5zdCBoeXBvY2hvbmRyaWEKICAgIGVuZAogICAgTm90ZSByaWdodCBvZiBKb2huOiBSYXRpb25hbCB0aG91Z2h0cyA8YnIvPnByZXZhaWwuLi4KICAgIEpvaG4tLT5BbGljZTogR3JlYXQhCiAgICBKb2huLT5Cb2I6IEhvdyBhYm91dCB5b3U_CiAgICBCb2ItLT5Kb2huOiBKb2xseSBnb29kIQ))
Link to Image

### CODE REVIEW

**Comment by zengxs** [comment]
This looks good. 👍 
Is it possible to support svg output?

**Comment by jihchi** [comment]
Hi @zengxs , Yes, It's possible, I'll add this feature.

**Comment by knsv** [comment]
Hi! I  am reworking the editor and in that work I will also add this link but there is an issue with the version of mermaid used by the service. Could you update the version?

**Comment by knsv** [comment]
I will close this pull request but will add the link in the updated editor.

**Pull request closed without merging**
